# Generated by Django 3.0.5 on 2020-06-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare_app', '0016_auto_20200622_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HealthCare_app.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HealthCare_app.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assignedDoctorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HealthCare_app.Doctor'),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='patientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HealthCare_app.Patient'),
        ),
    ]
